# Generated by Django 3.0.14 on 2021-10-07 00:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fichas', '0002_auto_20211006_1642'),
    ]

    operations = [
        migrations.CreateModel(
            name='Delito',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delito', models.CharField(help_text='Tarea.', max_length=70)),
            ],
        ),
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Estado del caso.', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='JuridiccionPolicial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Juridiccion Policial.', max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='dependencia',
            name='email',
            field=models.EmailField(help_text='Mail de la Fiscalia o dependencia.', max_length=254),
        ),
        migrations.AlterField(
            model_name='dependencia',
            name='name',
            field=models.CharField(help_text='Dependencia.', max_length=50),
        ),
        migrations.AlterField(
            model_name='fichas',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, help_text='Fecha Creacion.'),
        ),
        migrations.AlterField(
            model_name='fichas',
            name='date_edited',
            field=models.DateTimeField(help_text='Ultima edicion.', null=True),
        ),
        migrations.AlterField(
            model_name='fichas',
            name='dependencia',
            field=models.ForeignKey(help_text='Dependencia.', on_delete=django.db.models.deletion.CASCADE, to='fichas.Dependencia'),
        ),
        migrations.AlterField(
            model_name='origendenuncia',
            name='email',
            field=models.EmailField(help_text='Mail.', max_length=254),
        ),
        migrations.AlterField(
            model_name='origendenuncia',
            name='name',
            field=models.CharField(help_text='Origen de la Denuncia.', max_length=50),
        ),
        migrations.AlterField(
            model_name='tarea',
            name='title',
            field=models.CharField(help_text='Tarea.', max_length=70),
        ),
        migrations.CreateModel(
            name='Fiscales',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apellido', models.CharField(help_text='Apellido', max_length=50)),
                ('nombre', models.CharField(help_text='Nombre', max_length=50)),
                ('direccion', models.CharField(help_text='Direción', max_length=50)),
                ('email', models.EmailField(help_text='Mail del Fiscal', max_length=254)),
                ('telefono', models.CharField(help_text='Telefono', max_length=50)),
                ('dependencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fichas.Dependencia')),
            ],
        ),
        migrations.CreateModel(
            name='DatosDefensoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datos', models.CharField(help_text='Datos de la Defensoria.', max_length=70)),
                ('ficha', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fichas.Fichas')),
            ],
        ),
    ]
