# Generated by Django 3.0.14 on 2021-10-07 01:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fichas', '0003_auto_20211007_0047'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fiscale',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apellido', models.CharField(help_text='Apellido', max_length=50)),
                ('nombre', models.CharField(help_text='Nombre', max_length=50)),
                ('direccion', models.CharField(help_text='Dirección', max_length=50)),
                ('email', models.EmailField(help_text='Mail del Fiscal', max_length=254)),
                ('telefono', models.CharField(help_text='Telefono', max_length=50)),
                ('dependencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fichas.Dependencia')),
            ],
        ),
        migrations.RenameModel(
            old_name='Fichas',
            new_name='Ficha',
        ),
        migrations.RenameModel(
            old_name='JuridiccionPolicial',
            new_name='Juridiccione',
        ),
        migrations.DeleteModel(
            name='Fiscales',
        ),
    ]
