# Generated by Django 3.0.14 on 2021-10-21 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fichas', '0004_auto_20211007_0153'),
    ]

    operations = [
        migrations.AddField(
            model_name='dependencia',
            name='domicilio',
            field=models.CharField(blank=True, help_text='calle', max_length=50),
        ),
        migrations.AlterField(
            model_name='delito',
            name='delito',
            field=models.CharField(help_text='Tipo de delito.', max_length=70),
        ),
        migrations.AlterField(
            model_name='estado',
            name='name',
            field=models.CharField(help_text='Estado de Situacion.', max_length=50),
        ),
    ]
