# Generated by Django 3.0.14 on 2021-10-22 16:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fichas', '0005_auto_20211021_2359'),
    ]

    operations = [
        migrations.CreateModel(
            name='RolAdministrativo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rolAdministrativo', models.CharField(help_text='Rol Administrativo.', max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='origendenuncia',
            name='telefono',
            field=models.CharField(blank=True, help_text='Telefono', max_length=15),
        ),
        migrations.AlterField(
            model_name='dependencia',
            name='domicilio',
            field=models.CharField(blank=True, help_text='domicilio', max_length=50),
        ),
        migrations.AlterField(
            model_name='juridiccione',
            name='name',
            field=models.CharField(help_text='Juridiccion', max_length=50),
        ),
        migrations.CreateModel(
            name='Ubicacione',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ubicacion', models.CharField(help_text='Dependencia.', max_length=50)),
                ('idCaso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fichas.Ficha')),
                ('idDependencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fichas.Dependencia')),
            ],
        ),
        migrations.CreateModel(
            name='Localidade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Localidad.', max_length=50)),
                ('CP', models.CharField(blank=True, help_text='Codigo postal', max_length=6)),
                ('idjuridiccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fichas.Juridiccione')),
            ],
        ),
        migrations.CreateModel(
            name='JuridiccionesPoliciale',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Juridiccion Policial.', max_length=50)),
                ('idlocalidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fichas.Localidade')),
            ],
        ),
        migrations.CreateModel(
            name='Administrativo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.CharField(help_text='usuario.', max_length=70, unique=True)),
                ('apellido', models.CharField(help_text='apellido.', max_length=70)),
                ('nombre', models.CharField(help_text='nombre.', max_length=70)),
                ('telefono', models.CharField(help_text='telefono.', max_length=70)),
                ('mail', models.EmailField(help_text='mail.', max_length=30)),
                ('iddependencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fichas.Dependencia')),
            ],
        ),
        migrations.AddField(
            model_name='dependencia',
            name='idLocalidad',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='fichas.Localidade'),
            preserve_default=False,
        ),
    ]
