# Generated by Django 3.0.14 on 2021-10-22 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fichas', '0007_auto_20211022_2010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarea',
            name='nota',
            field=models.CharField(help_text='Nota', max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='tarea',
            name='resultado',
            field=models.FileField(help_text='resultado', null=True, upload_to=''),
        ),
    ]
