# Generated by Django 3.0.14 on 2021-10-22 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fichas', '0009_remove_ficha_observaciones'),
    ]

    operations = [
        migrations.AddField(
            model_name='ficha',
            name='Observacion',
            field=models.Field(blank=True, help_text='Resumen de la denuncia', max_length=300),
        ),
    ]
