# Generated by Django 3.0.14 on 2021-10-22 21:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fichas', '0010_ficha_observacion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ficha',
            old_name='Observacion',
            new_name='observacion',
        ),
    ]
